name: flutter_cubit_create_page
description: "A new Flutter project."
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  recase: ^4.1.0
  syntax_highlight: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Consolas
      fonts:
        - asset: assets/fonts/Consolas.ttf
          weight: 400